### PR TITLE
Patch.

### PR DESCRIPTION
**Pull request by Maikuolan**
Updates repository URLs.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Perfect, thanks.

**Comment by DanielRuf** [comment]
The Cloudflare cache is cleared and the changes are rolled out.

**Comment by Maikuolan** [comment]
Awesome! :-)

**Comment by DanielRuf** [comment]
Can you create another PR and add the website buttons to both using the github.io URLs?

**Comment by Maikuolan** [comment]
I'll do that now.

**Pull request merged**
